language: R
cache: packages

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
    - os: osx
  allow_failures:
    - os: osx

warnings_are_errors: false

r_packages:
  - maptools

r_github_packages:
  # - r-lib/covr
  - gastonstat/matrixkit

# before_install:
#   - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew install llvm; fi
#   - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then export PATH="/usr/local/opt/llvm/bin:$PATH"; fi
  
# after_success:
#   - Rscript -e 'covr::codecov()'
